/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab5p2_luismendoza;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author luiscarlomendoza
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_add = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_universo = new javax.swing.JComboBox<>();
        jt_poder = new javax.swing.JTextField();
        jt_debilidad = new javax.swing.JTextField();
        jt_fuerza = new javax.swing.JTextField();
        jt_nombre = new javax.swing.JTextField();
        jt_agilidadMental = new javax.swing.JTextField();
        jt_agilidadFisica = new javax.swing.JTextField();
        jt_vida = new javax.swing.JTextField();
        jb_guardarAdd = new javax.swing.JButton();
        jd_listar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree_lista = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_heroe = new javax.swing.JList<>();
        pp_heroe = new javax.swing.JPopupMenu();
        mi_modificar = new javax.swing.JMenuItem();
        mi_eliminar = new javax.swing.JMenuItem();
        jd_modificar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jt_poder2 = new javax.swing.JTextField();
        jt_nombre2 = new javax.swing.JTextField();
        jt_debilidad2 = new javax.swing.JTextField();
        jt_fuerza2 = new javax.swing.JTextField();
        jt_af2 = new javax.swing.JTextField();
        jt_vida2 = new javax.swing.JTextField();
        jt_am2 = new javax.swing.JTextField();
        jb_guardarModificar = new javax.swing.JButton();
        jd_batalla = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        cb_luchador1 = new javax.swing.JComboBox<>();
        cb_luchador2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_luchador1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_luchador2 = new javax.swing.JList<>();
        jb_battle = new javax.swing.JButton();
        jd_battle = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel3.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel3.setText("Poder");

        jLabel4.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel5.setText("Agilidad Mental");

        jLabel6.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel6.setText("Fuerza");

        jLabel7.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel7.setText("Agilidad Física");

        jLabel8.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel8.setText("Debilidad");

        jLabel9.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel9.setText("Vida");

        jLabel10.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel10.setText("Universo");

        cb_universo.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        cb_universo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marvel", "DC", "Capcom", "MK" }));

        jt_poder.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jt_debilidad.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jt_fuerza.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jt_nombre.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jt_agilidadMental.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jt_agilidadFisica.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jt_vida.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        jb_guardarAdd.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_guardarAdd.setText("Guardar");
        jb_guardarAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_guardarAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_agilidadMental, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(601, 601, 601))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jb_guardarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(805, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jt_agilidadFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(604, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_agilidadMental, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_guardarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(444, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(322, Short.MAX_VALUE)
                    .addComponent(jt_agilidadFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(190, 190, 190)))
        );

        javax.swing.GroupLayout jd_addLayout = new javax.swing.GroupLayout(jd_add.getContentPane());
        jd_add.getContentPane().setLayout(jd_addLayout);
        jd_addLayout.setHorizontalGroup(
            jd_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_addLayout.setVerticalGroup(
            jd_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        jLabel11.setFont(new java.awt.Font("Zapfino", 0, 24)); // NOI18N
        jLabel11.setText("Lista de Personajes");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jtree_lista.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree_lista);

        jl_heroe.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_heroe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mi_modificar.setText("Modificar");
        mi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarActionPerformed(evt);
            }
        });
        pp_heroe.add(mi_modificar);

        mi_eliminar.setText("Eliminar");
        mi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarActionPerformed(evt);
            }
        });
        pp_heroe.add(mi_eliminar);

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        jLabel12.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel12.setText("Poder");

        jLabel13.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel13.setText("Debilidad");

        jLabel14.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel14.setText("Fuerza");

        jLabel15.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel15.setText("Agilidad Fisica");

        jLabel16.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel16.setText("Agilidad Mental");

        jLabel17.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel17.setText("Vida");

        jLabel18.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel18.setText("Nombre");

        jb_guardarModificar.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_guardarModificar.setText("Guardar");
        jb_guardarModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_af2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jt_fuerza2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jt_poder2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jt_debilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jb_guardarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(659, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(jt_am2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(595, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_poder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_debilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_fuerza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_af2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jb_guardarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(464, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(330, Short.MAX_VALUE)
                    .addComponent(jt_am2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(214, 214, 214)))
        );

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));

        jl_luchador1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_luchador1);

        jl_luchador2.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_luchador2);

        jb_battle.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_battle.setText("Battle");
        jb_battle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_battle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_battleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_luchador2, 0, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(145, 145, 145)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_luchador1, 0, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(384, 384, 384))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jb_battle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_luchador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_luchador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(60, 60, 60)
                .addComponent(jb_battle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_batallaLayout = new javax.swing.GroupLayout(jd_batalla.getContentPane());
        jd_batalla.getContentPane().setLayout(jd_batallaLayout);
        jd_batallaLayout.setHorizontalGroup(
            jd_batallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_batallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_batallaLayout.setVerticalGroup(
            jd_batallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 0, 51));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane5.setViewportView(jTextArea);

        jButton4.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton4.setText("Atacar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_battleLayout = new javax.swing.GroupLayout(jd_battle.getContentPane());
        jd_battle.getContentPane().setLayout(jd_battleLayout);
        jd_battleLayout.setHorizontalGroup(
            jd_battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_battleLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_battleLayout.setVerticalGroup(
            jd_battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5p2_luismendoza/M v C.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Zapfino", 0, 24)); // NOI18N
        jLabel2.setText("Marvel vs DC vs Capcom vs MK ");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton1.setText("Listar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton3.setText("Agregar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton2.setText("Simulacion de Batalla");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(127, 127, 127)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

        jd_add.setModal(true);
        jd_add.pack();
        jd_add.setLocationRelativeTo(this);
        jd_add.setVisible(true);


    }//GEN-LAST:event_jButton3MouseClicked

    private void jb_guardarAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarAddMouseClicked
        // TODO add your handling code here:

        String n = jt_nombre.getText();
        String p = jt_poder.getText();
        String d = jt_debilidad.getText();

        int f = Integer.parseInt(jt_fuerza.getText());
        int af = Integer.parseInt(jt_agilidadFisica.getText());
        int am = Integer.parseInt(jt_agilidadMental.getText());
        int v = Integer.parseInt(jt_vida.getText());

        if (cb_universo.getSelectedItem().equals("Marvel")) {
            String m = (String) cb_universo.getSelectedItem();
            Personaje marvelPersonaje = new Personaje(n, p, d,
                    m, f, af, am, v);
            
            heroes.add(marvelPersonaje);
            marvel.add(marvelPersonaje);

            DefaultTreeModel modeloArbol
                    = (DefaultTreeModel) jtree_lista.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloArbol.getRoot();
            //obtener la persona a guardar

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(m)) {
                    DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(marvelPersonaje);
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p1);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n1 = new DefaultMutableTreeNode(m);
                DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(marvelPersonaje);
                n1.add(p1);
                raiz.add(n1);
            }  // fin if          
            modeloArbol.reload();

            JOptionPane.showMessageDialog(jd_add, "Se ha guardado con éxito");

        } else if (cb_universo.getSelectedItem().equals("DC")) {

            String m1 = (String) cb_universo.getSelectedItem();
            Personaje dcPersonaje = new Personaje(n, p, d,
                    m1, f, af, am, v);
            
            heroes.add(dcPersonaje);
            dc.add(dcPersonaje);

            DefaultTreeModel modeloArbol
                    = (DefaultTreeModel) jtree_lista.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloArbol.getRoot();
            //obtener la persona a guardar

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(m1)) {
                    DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(dcPersonaje);
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p1);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n1 = new DefaultMutableTreeNode(m1);
                DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(dcPersonaje);
                n1.add(p1);
                raiz.add(n1);
            }  // fin if          
            modeloArbol.reload();

            JOptionPane.showMessageDialog(jd_add, "Se ha guardado con éxito");

        } else if (cb_universo.getSelectedItem().equals("Capcom")) {

            String m2 = (String) cb_universo.getSelectedItem();
            Personaje capcomPersonaje = new Personaje(n, p, d,
                    m2, f, af, am, v);
            
            heroes.add(capcomPersonaje);
            capcom.add(capcomPersonaje);
            
            DefaultTreeModel modeloArbol
                    = (DefaultTreeModel) jtree_lista.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloArbol.getRoot();
            //obtener la persona a guardar
            
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(m2)) {
                    DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(capcomPersonaje);
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p1);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n1 = new DefaultMutableTreeNode(m2);
                DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(capcomPersonaje);
                n1.add(p1);
                raiz.add(n1);
            }  // fin if          
            modeloArbol.reload();

            JOptionPane.showMessageDialog(jd_add, "Se ha guardado con éxito");

        } else if (cb_universo.getSelectedItem().equals("MK")) {

            String m3 = (String) cb_universo.getSelectedItem();
            Personaje mkPersonaje = new Personaje(n, p, d,
                    m3, f, af, am, v);
            
            DefaultTreeModel modeloArbol
                    = (DefaultTreeModel) jtree_lista.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloArbol.getRoot();
            //obtener la persona a guardar
            
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(m3)) {
                    DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(mkPersonaje);
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p1);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n1 = new DefaultMutableTreeNode(m3);
                DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(mkPersonaje);
                n1.add(p1);
                raiz.add(n1);
            }  // fin if          
            modeloArbol.reload();
            
            heroes.add(mkPersonaje);
            mk.add(mkPersonaje);

            JOptionPane.showMessageDialog(jd_add, "Se ha guardado con éxito");

        } else {
            JOptionPane.showMessageDialog(jd_add,"Ocurrio un error");
        }
        
        jt_nombre.setText("");
        jt_poder.setText("");
        jt_debilidad.setText("");
        jt_fuerza.setText("");
        jt_agilidadFisica.setText("");
        jt_agilidadMental.setText("");
        jt_vida.setText("");
        

    }//GEN-LAST:event_jb_guardarAddMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        jd_listar.setModal(true);
        jd_listar.pack();
        jd_listar.setLocationRelativeTo(this);
        jd_listar.setVisible(true);


    }//GEN-LAST:event_jButton1MouseClicked

    private void jtree_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_listaMouseClicked
        // TODO add your handling code here:
        
        if (evt.getButton() == 3) {
            DefaultListModel modelo1 = (DefaultListModel) jl_heroe.getModel();
                modelo1.clear();
                jl_heroe.setModel(modelo1);
               
            //seleccionar un nodo con click derecho
            int row = jtree_lista.getClosestRowForLocation(evt.getX(), evt.getY());
            jtree_lista.setSelectionRow(row);
            Object v1
                    = jtree_lista.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Personaje) {

                personaje_seleccionada
                        = (Personaje) nodo_seleccionado.
                        getUserObject();
                pp_heroe.show(evt.getComponent(),evt.getX(), evt.getY());
                
                DefaultListModel modelo = (DefaultListModel) jl_heroe.getModel();
                modelo.addElement(personaje_seleccionada.toString2());
                jl_heroe.setModel(modelo);
                
            } else if(nodo_seleccionado.getUserObject() instanceof Personaje == false){

                
                
            }

        }
        
        
    }//GEN-LAST:event_jtree_listaMouseClicked

    private void mi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarActionPerformed
        // TODO add your handling code here:
        jd_listar.setVisible(false);
        jd_modificar.setModal(true);
        jd_modificar.pack();
        jd_modificar.setLocationRelativeTo(jd_listar);
        jd_modificar.setVisible(true);
        
    }//GEN-LAST:event_mi_modificarActionPerformed

    private void mi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                pp_heroe,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) jtree_lista.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
        
        DefaultListModel modelo1 = (DefaultListModel) jl_heroe.getModel();
        modelo1.clear();
        jl_heroe.setModel(modelo1);
        
        for (int i = 0; i < heroes.size(); i++) {
            
            if(personaje_seleccionada.getNombre().equalsIgnoreCase(heroes.get(i).getNombre())){
                heroes.remove(i);
            }
            
        }
        
        
    }//GEN-LAST:event_mi_eliminarActionPerformed

    private void jb_guardarModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarModificarMouseClicked
        // TODO add your handling code here:
        
        for (int i = 0; i < heroes.size(); i++) {
            
            if(personaje_seleccionada.getNombre().equalsIgnoreCase(heroes.get(i).getNombre())){
                heroes.remove(i);
            }
        
        
        DefaultListModel modelo1 = (DefaultListModel) jl_heroe.getModel();
                modelo1.clear();
                jl_heroe.setModel(modelo1);
        
        personaje_seleccionada.setNombre(jt_nombre2.getText());
        DefaultTreeModel m = (DefaultTreeModel) jtree_lista.getModel();
        m.reload();
        
        personaje_seleccionada.setPoder(jt_poder2.getText());
        personaje_seleccionada.setDebilidad(jt_debilidad2.getText());
        personaje_seleccionada.setFuerza(Integer.parseInt(jt_fuerza2.getText()));
        personaje_seleccionada.setAgilidadFisica(Integer.parseInt(jt_af2.getText()));
        personaje_seleccionada.setAgilidadMental(Integer.parseInt(jt_am2.getText()));
        personaje_seleccionada.setVida(Integer.parseInt(jt_vida2.getText()));
        
        heroes.add(personaje_seleccionada);
        
        JOptionPane.showMessageDialog(jd_modificar, "Se modifico con éxito");
              
        jd_modificar.setVisible(false);
                
        jd_listar.setVisible(true);
        
        
    }//GEN-LAST:event_jb_guardarModificarMouseClicked
    
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO
        
        
        
        for (int i = 0; i < heroes.size(); i++) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_luchador1.getModel();
            modelo.addElement(heroes.get(i));
            cb_luchador1.setModel(modelo);
            
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_luchador2.getModel();
            modelo2.addElement(heroes.get(i));
            cb_luchador2.setModel(modelo2);
            
        }
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_luchador1.getModel();
        DefaultListModel m = (DefaultListModel) jl_luchador1.getModel();
        m.addElement(modelo.getSelectedItem());
        jl_luchador1.setModel(m);
        
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_luchador2.getModel();
        DefaultListModel m1 = (DefaultListModel) jl_luchador2.getModel();
        m1.addElement(modelo2.getSelectedItem());
        jl_luchador2.setModel(m1);
        
        jd_batalla.setModal(true);
        jd_batalla.pack();
        jd_batalla.setLocationRelativeTo(this);
        jd_batalla.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_battleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_battleMouseClicked
        // TODO add your handling code here:
        Personaje luchador1 =  (Personaje)cb_luchador1.getSelectedItem();
        Personaje luchador2 = (Personaje)cb_luchador2.getSelectedItem();
        
        String vida1 = Integer.toString(luchador1.getVida());
        String vida2 = Integer.toString(luchador2.getVida());
        
        jTextArea.setText(luchador1.getNombre() + " = " + vida1 + "\n" +
                luchador2.getNombre() + " = " + vida2 + "\n");
        
        jd_battle.setModal(true);
        jd_battle.pack();
        jd_battle.setLocationRelativeTo(this);
        jd_battle.setVisible(true);
        
        
        
    }//GEN-LAST:event_jb_battleMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton4MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_luchador1;
    private javax.swing.JComboBox<String> cb_luchador2;
    private javax.swing.JComboBox<String> cb_universo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JButton jb_battle;
    private javax.swing.JButton jb_guardarAdd;
    private javax.swing.JButton jb_guardarModificar;
    private javax.swing.JDialog jd_add;
    private javax.swing.JDialog jd_batalla;
    private javax.swing.JDialog jd_battle;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JList<String> jl_heroe;
    private javax.swing.JList<String> jl_luchador1;
    private javax.swing.JList<String> jl_luchador2;
    private javax.swing.JTextField jt_af2;
    private javax.swing.JTextField jt_agilidadFisica;
    private javax.swing.JTextField jt_agilidadMental;
    private javax.swing.JTextField jt_am2;
    private javax.swing.JTextField jt_debilidad;
    private javax.swing.JTextField jt_debilidad2;
    private javax.swing.JTextField jt_fuerza;
    private javax.swing.JTextField jt_fuerza2;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombre2;
    private javax.swing.JTextField jt_poder;
    private javax.swing.JTextField jt_poder2;
    private javax.swing.JTextField jt_vida;
    private javax.swing.JTextField jt_vida2;
    private javax.swing.JTree jtree_lista;
    private javax.swing.JMenuItem mi_eliminar;
    private javax.swing.JMenuItem mi_modificar;
    private javax.swing.JPopupMenu pp_heroe;
    // End of variables declaration//GEN-END:variables

    // Mis Variables
    ArrayList<Personaje> heroes = new ArrayList();
    ArrayList<Personaje> marvel = new ArrayList();
    ArrayList<Personaje> dc = new ArrayList();
    ArrayList<Personaje> capcom = new ArrayList();
    ArrayList<Personaje> mk = new ArrayList();

    DefaultMutableTreeNode nodo_seleccionado;
    Personaje personaje_seleccionada;
    
    
}
